psdk_wrapper_node:
  ros__parameters:
    liveview:
      is_enable: False
      camera_index: 1
      topic_name: "/sensor/camera"
      is_display: false
      mp4_output_folder: "$(find-pkg-share payload_sdk_ros2)/recordings"
      enable_recording_server_name: "/psdk_wrapper_node/enable_recording"

    flight_control:
      is_enable: True